version: '2'
services:
  cm:
    image: cdh:full
    hostname: cm
    ports:
      - 7180:7180
    command: /cmstart.sh
  agent1:
    image: cdh:full
    hostname: agent1
    ports:
      - 8088:8088
      - 8888:8888
      - 7070:7070
      - 8032:8032
      - 2181:2181
    volumes:
      - ./src/:/src
      - /data/agent1/:/data
    ulimits:
        nofile: 262144
        memlock: 2000000000
    command: /agentstart.sh
  agent2:
    image: cdh:full
    hostname: agent2
    ports:
      - 9092:9092
    volumes:
      - /data/agent2/:/data
    ulimits:
        nofile: 262144
        memlock: 2000000000
    command: /agentstart.sh
  agent3:
    image: cdh:full
    hostname: agent3
    ulimits:
        nofile: 262144
        memlock: 2000000000
    volumes:
      - /data/agent3/:/data
    command: /agentstart.sh
   
